apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgmt
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: mgmt
  template:
    metadata:
      labels:
        app: mgmt   
    spec:
      containers:
      - name: mgmt
        image: nginx:1.15.4
---
kind: Service
apiVersion: v1
metadata:
  name: mgmt-svc
spec:
  type: LoadBalancer
  selector:
    app: mgmt
  ports:
  - protocol: TCP
    name: mgmt
    port: 80
    targetPort: 80
